dataset: edge_colors
model:
  num_layers: 3
  mini_layers: 0
  mlp_layers: 2
  embs: (0, 1, 2)
  embs_combine_mode: 'concat'
  pool: add
subgraph:
  hops: 7
  online: False
train:
  lr: 0.001
  epochs: 250
  runs: 1
  lr_patience: 40
eigel:
  reuse_embeddings: 'all'
