dataset: Proximity
train:
  batch_size: 32
  lr_patience: 20
  epochs: 50

model:
  mini_layers: 1
  hidden_size: 64
  num_layers: 3
  pool: add
  embs: (0, 1, 2)
  embs_combine_mode: 'concat'

subgraph:
  hops: 3
