dataset: Proximity
train:
  batch_size: 16
  lr_patience: 10
  epochs: 30

elene:
  reuse_embeddings: "all"

model:
  mini_layers: 1
  hidden_size: 64
  mlp_layers: 2
  num_layers: 3
  pool: add
  embs: (0, 1, 2)
  embs_combine_mode: 'concat'

subgraph:
  hops: 5
